/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 comp_house.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function House(props) {
  const { nodes, materials } = useGLTF("assets/comp_house.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={[1, 1.5, 1]}
      position={[-28, -2.7, -1]}
    >
      <mesh geometry={nodes.Cube.geometry} material={materials.Material}>
        <meshStandardMaterial wireframe color={"red"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("assets/comp_house.glb");
